include(ExternalProject)
ExternalProject_Add( 
  Catch2
  PREFIX Catch2
  URL "https://github.com/catchorg/Catch2/archive/refs/tags/v3.3.2.zip"
  INSTALL_DIR ${CMAKE_CURRENT_BINARY_DIR}
  CMAKE_ARGS
  "-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>"
  "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
  "-DCATCH_INSTALL_DOCS=OFF"
  "-DCATCH_INSTALL_EXTRAS=OFF"
  "-DINSTALL_PATH=install"
  )

ExternalProject_Get_Property(Catch2 INSTALL_DIR)

set(CATCH2_INCLUDES
  ${INSTALL_DIR}/include
  )
set(CATCH2_LIBRARIES 
  ${INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}Catch2d${CMAKE_STATIC_LIBRARY_SUFFIX}
  )

set(CATCH_INCLUDES ${CATCH2_INCLUDES} CACHE STRING "")
set(CATCH_LIBRARIES ${CATCH2_LIBRARIES} CACHE STRING "")
